// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package deserialize

import "fmt"

const _DataType_name = "INTUINTFLOATBOOLBYTESBIN"

var _DataType_index = [...]uint8{0, 3, 7, 12, 16, 21, 24}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return fmt.Sprintf("DataType(%d)", i)
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
