// Code generated by "stringer -type=EventCode"; DO NOT EDIT.

package table

import "fmt"

const _EventCode_name = "WE_ELEMENT_DESCRIPTORWE_REPLICATION_DESCRIPTORWE_OPERATOR_DESCRIPTORWE_SEQUENCE_DESCRIPTORWE_FACTORWE_BEGIN_SEQUENCEWE_END_SEQUENCEWE_BEGIN_REPLICATIONWE_END_REPLICATIONWE_BEGIN_BLOCKWE_END_BLOCKWE_BEGIN_TEMPLATEWE_END_TEMPLATE"

var _EventCode_index = [...]uint8{0, 21, 46, 68, 90, 99, 116, 131, 151, 169, 183, 195, 212, 227}

func (i EventCode) String() string {
	if i < 0 || i >= EventCode(len(_EventCode_index)-1) {
		return fmt.Sprintf("EventCode(%d)", i)
	}
	return _EventCode_name[_EventCode_index[i]:_EventCode_index[i+1]]
}
