// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package table

import "fmt"

const (
	_Operator_name_0 = "OP_NBITS_OFFSETOP_SCALE_OFFSETOP_NEW_REFVALOP_ASSOCIATE_FIELDOP_INSERT_STRINGOP_SKIP_LOCALOP_MODIFY_PACKINGOP_SET_STRING_LENGTH"
	_Operator_name_1 = "OP_DATA_NOT_PRESENTOP_QUALITY_INFOOP_SUBSTITUTIONOP_FIRST_ORDER_STATSOP_DIFFERENCE_STATS"
	_Operator_name_2 = "OP_REPLACEMENT"
	_Operator_name_3 = "OP_CANCEL_BACK_REFERENCEOP_DEFINE_BITMAPOP_RECALL_BITMAP"
	_Operator_name_4 = "OP_DEFINE_EVENTOP_DEFINE_CONDITIONING_EVENTOP_CATEGORICAL_VALUES"
)

var (
	_Operator_index_0 = [...]uint8{0, 15, 30, 43, 61, 77, 90, 107, 127}
	_Operator_index_1 = [...]uint8{0, 19, 34, 49, 69, 88}
	_Operator_index_2 = [...]uint8{0, 14}
	_Operator_index_3 = [...]uint8{0, 24, 40, 56}
	_Operator_index_4 = [...]uint8{0, 15, 43, 64}
)

func (i Operator) String() string {
	switch {
	case 201 <= i && i <= 208:
		i -= 201
		return _Operator_name_0[_Operator_index_0[i]:_Operator_index_0[i+1]]
	case 221 <= i && i <= 225:
		i -= 221
		return _Operator_name_1[_Operator_index_1[i]:_Operator_index_1[i+1]]
	case i == 232:
		return _Operator_name_2
	case 235 <= i && i <= 237:
		i -= 235
		return _Operator_name_3[_Operator_index_3[i]:_Operator_index_3[i+1]]
	case 241 <= i && i <= 243:
		i -= 241
		return _Operator_name_4[_Operator_index_4[i]:_Operator_index_4[i+1]]
	default:
		return fmt.Sprintf("Operator(%d)", i)
	}
}
